version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: canteen-db
    restart: always
    environment:
      POSTGRES_DB: smartcanteen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: canteen-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env